### ISSUE TITLE
Last message repeats

### ISSUE THREAD

**Issue by CanvasWhitewolf** [Er1807/MuteTTS#3]
Sometimes when I write a new message and send it for MuteTTS to speak it instead speaks the message that it last spoke before. How often it happens seems to correlate with how laggy the game is at that time.

**Comment by Er1807** [comment]
Gonna check it out during the weekend

**Comment by Er1807** [comment]
Please if it occurs again send me the melonloader log

**Comment by CanvasWhitewolf** [comment]
in this short video i try to say the numbers from 1 to 10, but instead of saying 7 it says 6 a second time:
https://www.youtube.com/watch?v=kLsWynKr56s

The corresponding melonloader log:
[MuteTTS repeat bug.log](https://github.com/Er1807/MuteTTS/files/7620514/MuteTTS.repeat.bug.log)
6s

**Comment by Er1807** [comment]
Thank, can you retry it with the latest version? @CanvasWhitewolf 
https://github.com/Er1807/MuteTTS/releases/tag/v1.0.6

Also please wait till it plays before executing the next

**Comment by Er1807** [comment]
Solved in newest release
