### ISSUE TITLE
Frozen Menu and Movement

### ISSUE THREAD

**Issue by HauntedC** [Er1807/MuteTTS#6]
When I click the MuteTTS in my radial menu it freezes the entire menu and wont let me exit it or move.
please fix I need this mod :(

*This issue started when VRChat made the UI Update.

**Comment by Er1807** [comment]
Hi @HauntedC, please provide me with a logfile so I can trace the error. This makes it way easier for me

**Comment by HauntedC** [comment]
Hi Eric a friend made it work for me thanks tho! <3 much love

Am Mo., 31. Jan. 2022 um 23:22 Uhr schrieb Eric van Fandenfart <
***@***.***>:
