### ISSUE TITLE
Typing space (hitting the space bar) does an in place jumping animation

### ISSUE THREAD

**Issue by CanvasWhitewolf** [Er1807/MuteTTS#8]
also crouching when hitting c
and proning when hitting z (y on my german keyboard).

**Comment by CanvasWhitewolf** [comment]
this problem still exists. why is there no reaction by the developer?

**Comment by Er1807** [comment]
Hi, sry all of my mods are now handeld via my discord https://discord.gg/Jq2A3P6jjs as this is way easier to get opiniones from a lot of people. 
Also MuteTTS is a smaller mode with less peopole using it so issues on that one dont too high of a priority.
