### ISSUE TITLE
Text Box Issues

### ISSUE THREAD

**Issue by Lexian-droid** [Er1807/MuteTTS#9]
Hello, I found this plugin from something called MelonAssistent, loving it so far, However I notice a small problem that seems to happen when on PC, the problem is, I seem to be able to still crouch and whatnot when typing in the text box, this is a bit difficult to deal with if i'm typing in desktop mode, I know it's probably meant to be used in VR, but it would be nice if this was fixed either way.

Good plugin nonetheless, though.

**Comment by Lexian-droid** [comment]
Edit: The same problem also exist when crawling, and jumping, forgot to mention that, my bad.

**Comment by Er1807** [comment]
Hi, already fixed in the newest version. Check releases. The vrcmg release is still waiting approval
